name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - arpit # Adjusted to trigger on pushes to master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: arpitblagan/piroo:latest

      - name: Verify Pushed Image
        run: docker pull arpitblagan/piroo:latest

      - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull arpitblagan/piroo:latest
          sudo docker stop piroo || true
          sudo docker rm piroo || true
          sudo docker run -d --name piroo -p 3005:3000 arpitblagan/piroo:latest